version: '3.4'

services:
  web:
    build:
      context: ./web 
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    environment:
      REACT_APP_NODE_ENV: production
    env_file:
      - ./web/.env

  server:
    build: 
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./server/.env 